language: go
sudo: false
git:
  depth: 1
notifications:
  email: false

go:
- "1.12"
- "1.13"

before_install:
  - go get -t -v ./...
  
script:
  - go vet .
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
