FROM golang:1.11

COPY . /go-fsevents/src/github.com/tywkeene/go-fsevents

WORKDIR /go-fsevents/src/github.com/tywkeene/go-fsevents
RUN go mod download

ENV GOPATH="/go-fsevents" 
CMD go test -v ./...
